version: '3.8'

services:
  db:
    image: postgres:16-alpine 
    restart: always 
    environment:
      POSTGRES_DB: ishowdhb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata: # Defines the named volume for PostgreSQL data
  pgadmin_data: # Defines the named volume for pgAdmin data